import { useEffect, useState } from 'react';
import { ClipboardCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../services/api.js';
import useReferenceData from '../hooks/useReferenceData.js';
import OperationForm from '../components/OperationForm.jsx';
import DataTable, { formatDate } from '../components/DataTable.jsx';

export default function Assignments() {
  const { user } = useAuth(); const { reference, error: refError } = useReferenceData(); const [assignments, setAssignments] = useState([]); const [expenditures, setExpenditures] = useState([]); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const load = () => Promise.all([api.assignments(user), api.expenditures(user)]).then(([assignmentResult, expenditureResult]) => { setAssignments(assignmentResult.assignments); setExpenditures(expenditureResult.expenditures); }).catch((failure) => setError(failure.message));
  useEffect(load, [user]);
  const submit = (method, success) => async (data) => { setError(''); try { await method(user, data); setMessage(success); load(); } catch (failure) { setError(failure.message); } };
  return <><header className="page-header"><div><p className="eyebrow">ISSUE & CONSUMPTION CONTROL</p><h1>Assignments & expenditure</h1><span>Record assets issued to units or consumed during authorized operations.</span></div><ClipboardCheck size={28} /></header>{(error || refError) && <p className="form-error">{error || refError}</p>}{message && <p className="success-message">{message}</p>}<section className="operation-grid"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">PERSONNEL / UNIT ISSUE</p><h2>Record assignment</h2></div></div>{reference.bases.length ? <OperationForm type="assignment" reference={reference} user={user} onSubmit={submit(api.createAssignment, 'Assignment recorded and available stock updated.')} /> : <div className="loading-card">Loading form…</div>}</article><article className="panel"><div className="panel-heading"><div><p className="eyebrow">CONSUMPTION</p><h2>Record expenditure</h2></div></div>{reference.bases.length ? <OperationForm type="expenditure" reference={reference} user={user} onSubmit={submit(api.createExpenditure, 'Expenditure recorded and available stock updated.')} /> : <div className="loading-card">Loading form…</div>}</article></section><section className="dashboard-grid"><article className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">ASSIGNMENT REGISTER</p><h2>Recent assignments</h2></div></div><DataTable rows={assignments} columns={[{ label: 'Date', render: (row) => formatDate(row.createdAt) }, { label: 'Base', render: (row) => row.base.name }, { label: 'Equipment', render: (row) => row.equipmentType.name }, { label: 'Assignee', key: 'assignee' }, { label: 'Quantity', render: (row) => row.quantity.toLocaleString() }]} /></article><article className="panel table-panel"><div className="panel-heading"><div><p className="eyebrow">EXPENDITURE REGISTER</p><h2>Recent expenditure</h2></div></div><DataTable rows={expenditures} columns={[{ label: 'Date', render: (row) => formatDate(row.createdAt) }, { label: 'Base', render: (row) => row.base.name }, { label: 'Equipment', render: (row) => row.equipmentType.name }, { label: 'Reason', key: 'reason' }, { label: 'Quantity', render: (row) => row.quantity.toLocaleString() }]} /></article></section></>;
}
