import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, ResponsiveContainer, Tooltip } from 'recharts';
import { ArrowLeftRight, Box, ClipboardCheck, PackageMinus, RefreshCw, ShieldCheck } from 'lucide-react';
import { useAuth } from '../context/AuthContext.jsx';
import { api } from '../services/api.js';
import useReferenceData from '../hooks/useReferenceData.js';
import MetricCard from '../components/MetricCard.jsx';
import NetMoveModal from '../components/NetMoveModal.jsx';
import DataTable from '../components/DataTable.jsx';

export default function Dashboard() {
  const { user } = useAuth(); const { reference, error: referenceError } = useReferenceData();
  const [filters, setFilters] = useState({ baseId: user.baseId || '', equipmentTypeId: '', startDate: '', endDate: '' });
  const [metrics, setMetrics] = useState(null); const [assets, setAssets] = useState([]); const [error, setError] = useState(''); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); setError(''); try { const [dashboard, inventory] = await Promise.all([api.dashboard(user, filters), api.inventory(user, filters)]); setMetrics(dashboard); setAssets(inventory.assets); } catch (failure) { setError(failure.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [filters.baseId, filters.equipmentTypeId, filters.startDate, filters.endDate]);
  const chartData = useMemo(() => metrics ? [0.3, 0.45, 0.38, 0.55, 0.49, 0.67, 0.62, 0.76].map((weight, index) => ({ index, value: Math.max(0, Math.round(metrics.openingBalance + (metrics.closingBalance - metrics.openingBalance) * weight)) })) : [], [metrics]);
  const setFilter = (event) => setFilters((current) => ({ ...current, [event.target.name]: event.target.value }));
  return <><header className="page-header"><div><p className="eyebrow">COMMAND CENTER / OVERVIEW</p><h1>Operational overview</h1><span>Real-time inventory equation across your authorized command scope.</span></div><button className="secondary-button" onClick={load}><RefreshCw size={16} />Refresh</button></header>
    <section className="filter-bar"><label>Base<select name="baseId" value={filters.baseId} onChange={setFilter} disabled={user.role === 'BASE_COMMANDER'}><option value="">All bases</option>{reference.bases.map((base) => <option key={base.id} value={base.id}>{base.name}</option>)}</select></label><label>Equipment<select name="equipmentTypeId" value={filters.equipmentTypeId} onChange={setFilter}><option value="">All equipment</option>{reference.equipmentTypes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>From<input type="date" name="startDate" value={filters.startDate} onChange={setFilter} /></label><label>To<input type="date" name="endDate" value={filters.endDate} onChange={setFilter} /></label></section>
    {(error || referenceError) && <p className="form-error">{error || referenceError}</p>}{loading || !metrics ? <div className="loading-card">Loading authorized inventory data…</div> : <>
      <section className="metric-grid"><MetricCard label="Opening balance" value={metrics.openingBalance} caption="At period start" tone="slate" /><MetricCard label="Net movement" value={metrics.netMovement} caption="View purchase and transfer detail" tone="green" onClick={() => setModal(true)} /><MetricCard label="Assigned" value={metrics.assigned} caption="Issued to personnel / units" tone="blue" /><MetricCard label="Expended" value={metrics.expended} caption="Recorded consumed assets" tone="amber" /><MetricCard label="Closing balance" value={metrics.closingBalance} caption="Available after all operations" tone="purple" /></section>
      <section className="dashboard-grid"><article className="panel chart-panel"><div className="panel-heading"><div><p className="eyebrow">BALANCE TREND</p><h2>Inventory posture</h2></div><strong>{metrics.closingBalance.toLocaleString()} <small>closing units</small></strong></div><ResponsiveContainer width="100%" height={220}><AreaChart data={chartData}><defs><linearGradient id="balance" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#2f67d8" stopOpacity=".36" /><stop offset="1" stopColor="#2f67d8" stopOpacity="0" /></linearGradient></defs><Tooltip formatter={(value) => Number(value).toLocaleString()} /><Area type="monotone" dataKey="value" stroke="#2f67d8" strokeWidth={3} fill="url(#balance)" /></AreaChart></ResponsiveContainer><div className="formula">Closing = Opening + Purchases + Transfers In − Transfers Out − Assigned − Expended</div></article>
        <article className="panel movement-panel"><p className="eyebrow">MOVEMENT SUMMARY</p><h2>Net movement</h2><strong className="movement-value">+{metrics.netMovement.toLocaleString()} <small>units</small></strong><div className="movement-lines"><span><Box size={15} />Purchases <b>+{metrics.purchases.toLocaleString()}</b></span><span><ArrowLeftRight size={15} />Transfers in <b>+{metrics.transfersIn.toLocaleString()}</b></span><span><PackageMinus size={15} />Transfers out <b className="danger">−{metrics.transfersOut.toLocaleString()}</b></span><span><ClipboardCheck size={15} />Assigned & expended <b className="danger">−{(metrics.assigned + metrics.expended).toLocaleString()}</b></span></div></article>
      </section><section className="panel inventory-panel"><div className="panel-heading"><div><p className="eyebrow">CURRENT STOCK</p><h2>Available assets by base</h2></div><ShieldCheck color="#2f67d8" /></div><DataTable rows={assets} columns={[{ label: 'Base', render: (row) => row.base.name }, { label: 'Equipment', render: (row) => row.equipmentType.name }, { label: 'Category', render: (row) => <span className="tag">{row.equipmentType.category}</span> }, { label: 'Available', render: (row) => <b>{row.quantity.toLocaleString()}</b> }]} /></section>
    </>}{modal && <NetMoveModal metrics={metrics} onClose={() => setModal(false)} />}</>;
}
